# Generated by Django 5.1.6 on 2025-03-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groceries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruits', models.CharField(max_length=50)),
                ('vegetables', models.CharField(max_length=50)),
                ('oil', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'mydata',
            },
        ),
    ]
