# Generated by Django 5.1.6 on 2025-03-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('profile_image', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'accountinfo',
            },
        ),
    ]
